/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#e2e2e2",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "inverse-primary": "#ffb5a0",
        "tertiary-fixed-dim": "#86cfff",
        "secondary-container": "#e2e2e2",
        "inverse-surface": "#2f3131",
        "primary-container": "#ff5722",
        "primary": "#b02f00",
        "on-tertiary-fixed": "#001e2e",
        "on-secondary": "#ffffff",
        "secondary": "#5e5e5e",
        "primary-fixed-dim": "#ffb5a0",
        "surface": "#f9f9f9",
        "on-background": "#1a1c1c",
        "primary-fixed": "#ffdbd1",
        "surface-container-low": "#f3f3f4",
        "on-secondary-fixed": "#1b1b1b",
        "on-tertiary-fixed-variant": "#004c6d",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#f0f1f1",
        "secondary-fixed-dim": "#c6c6c6",
        "secondary-fixed": "#e2e2e2",
        "surface-container-high": "#e8e8e8",
        "on-surface": "#1a1c1c",
        "surface-dim": "#dadada",
        "surface-bright": "#f9f9f9",
        "on-primary-fixed-variant": "#862200",
        "error": "#ba1a1a",
        "surface-variant": "#e2e2e2",
        "on-surface-variant": "#5b4039",
        "on-error": "#ffffff",
        "background": "#f9f9f9",
        "on-primary-container": "#541200",
        "on-tertiary-container": "#fcfcff",
        "on-secondary-fixed-variant": "#474747",
        "on-primary-fixed": "#3b0900",
        "tertiary": "#00628c",
        "on-tertiary": "#ffffff",
        "surface-tint": "#b02f00",
        "on-error-container": "#93000a",
        "outline": "#907067",
        "on-secondary-container": "#646464",
        "tertiary-fixed": "#c8e6ff",
        "surface-container": "#eeeeee",
        "outline-variant": "#e4beb4",
        "tertiary-container": "#007caf"
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
